config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  resources :users, only: [:new, :create]

  get    '/email', to: 'notifications#show'
  post   '/notifications', to: 'notifications#create'

  resources :links, only: [:index, :create, :edit, :update]

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post "/links/:id", to: "links#update"
      get  "/index", to: "links#index"
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, presence: true
  validates :url, :format => URI::regexp(%w(http https)), presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email_address, uniqueness: true, presence: true
  validates :password, presence: true, length: { in: 3..15 }, confirmation: true

  has_secure_password
  has_many :links
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  respond_to :json

  def update
    link = Link.find(params[:id])
    link.update(read: !link.read)
    respond_with link
  end

  def index
    respond_with current_user.links
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    redirect_to login_path unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!

  def index
    @links = current_user.links
  end

  def create
    @link = Link.create(title: params[:link][:title], url: params[:link][:url], user_id: current_user.id)

    if @link.save
      flash[:success] = "You've created a new link"
      redirect_to :back
    else
      flash[:danger] = "There was problem creating your link, try again"
      redirect_to :back
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    @link.update(title: params[:link][:title], url: params[:link][:url], user_id: current_user.id)

    if @link.save
      flash[:success] = "Successfully Updated!"
      redirect_to links_path
    else
      flash[:danger] = "Please enter a valid URL"
      render :edit
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def show
    @link_url = params[:link_url]
  end

  def create
    NotificationsMailer.contact(email_params).deliver_now
    redirect_to :back, notice: "Email Sent!"
  end

  private

  def email_params
    params.permit(:name, :email, :message)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email_address: params[:session][:email_address])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back, #{user.email_address}!"
      redirect_to links_path
    else
      flash[:danger] = "Invalid username or password"
      redirect_to :back
    end
  end

  def destroy
    session.clear
    flash[:success] = "You have succesfully logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.create
  end

  def create
    user = User.create(user_params)
    user.save
    session[:user_id] = user.id
    redirect_to links_path
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password)
  end
end

app/helpers/api/v1/links_helper.rb
module Api::V1::LinksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/show.html.erb
<%= link_to "Login", login_path %>
<%= link_to "Sign Up", new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalCountdown</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "alert alert-success" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<h2>Edit Link</h2>

<%= form_for @link do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit "Update Link", id: "edit-link-button"%>
<% end %>

app/views/links/index.html.erb
<%= link_to "Logout", logout_path, method: :delete %>

<h4>Add Link</h4>
<%= form_for(:link, url: links_path) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>

  <%= f.label :url %>
  <%= f.text_field :url %> <br>

  <%= f.submit "Add Link" %>
<% end %>
<br>

<div class="filter">
  <label>Filter By Title</label>
  <%= text_field :link, :filter_title %>
  <button class="sort-alpha ascending">Sort Ascending</button>
  <button class="sort-alpha descending">Sort Descending</button>
  <label>Filter By Status</label>
  <select id="link_filter_status">
    <option value="empty"></option>
    <option value="true">Read</option>
    <option value="false">Unread</option>
  </select>
</div><br>

<div id="links">YOUR LINKS
   <% @links.each do |link| %>
    <div class="link" data-title="<%= link.title %>" data-status="<%= link.read %>">Title:
      <h6><%= link.title %></h6>URL:
      <% if link.read == false %>
        <span data="<%= link.id %>"><%= link.url %></span>
        <button class="read-status" data="<%= link.id %>">Mark As Read</button>
      <% else %>
        <span class="line-through-link" data="<%= link.id %>"><%= link.url %></span>
        <button class="read-status" data="<%= link.id %>">Mark As Unread</button>
      <% end %>
      <%= link_to "Recommend Link", email_path(link_url: link.url) %>
      <%= link_to "Edit", edit_link_path(link) %>
    </div>
  <% end %>
</div>
<hr>

app/views/notifications/show.html.erb
<div class="container">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <h1>Recommend Link To Friend!</h1>
    <hr>
    <%= form_tag "/notifications" do %>
      <div class="form-group">
        <%= label_tag :email %>
        <%= text_field_tag :email, "", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :name %>
        <%= text_field_tag :name, "", class: "form-control"  %>
      </div>
      <div class="form-group">
        <%= label_tag :message %>
        <%= text_area_tag :message, @link_url, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= submit_tag "Send Email", class: "btn btn-success form-control" %>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
  </div>
</div>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label      :email_address %>
  <%= f.text_field :email_address %><br>

  <%= f.label          :password %>
  <%= f.password_field :password %><br>

  <%= f.label          :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Sign Up" %>
<% end %>